version: "3.7"

volumes:
  data:

services:
  db:
    image: postgres:12.4-alpine
    env_file: ./src/.env
    ports:
      - 5432:5432
    volumes:
      - ./src:/app
  app:
    build:
      context: ./src
      dockerfile: ./Dockerfile-dev
    environment:
      DJANGO_DEBUG: 1
      DJANGO_SETTINGS_MODULE: conf.settings
    ports:
        - 8080:8080
    volumes:
      - ./src:/app
    depends_on:
      - db
  mail:
    image: mailhog/mailhog:v1.0.1
    ports:
        - 8025:8025
  djangoq:
    build:
      context: ./src
      dockerfile: ./Dockerfile-dev
    command: python manage.py qcluster
    volumes:
      - ./src:/app
    depends_on:
      - app