version: "3.7"

volumes:
  data:

services:
  app:
    build:
      context: ./src
    env_file: ./src/.env
    environment:
        - PYTHONUNBUFFERED=1
  redis:
    image: redis:6.0-rc4-alpine
    command: redis-server
